"""
Tests for configuration constants

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import unittest

from ap_copy_master_to_blink.config import (
    SUPPORTED_EXTENSIONS,
    TYPE_MASTER_DARK,
    TYPE_MASTER_FLAT,
    TYPE_MASTER_BIAS,
    DARK_MATCHING_KEYWORDS,
    FLAT_MATCHING_KEYWORDS,
    BIAS_MATCHING_KEYWORDS,
    KEYWORD_CAMERA,
    KEYWORD_GAIN,
    KEYWORD_OFFSET,
    KEYWORD_SETTEMP,
    KEYWORD_READOUTMODE,
    KEYWORD_EXPOSURESECONDS,
    KEYWORD_DATE,
    KEYWORD_FILTER,
)


class TestConfig(unittest.TestCase):
    """Test configuration constants."""

    def test_supported_extensions(self):
        """Test supported file extensions."""
        self.assertIn(".fits", SUPPORTED_EXTENSIONS)
        self.assertIn(".fit", SUPPORTED_EXTENSIONS)
        self.assertIn(".xisf", SUPPORTED_EXTENSIONS)

    def test_master_types(self):
        """Test master frame type constants."""
        self.assertEqual(TYPE_MASTER_DARK, "MASTER DARK")
        self.assertEqual(TYPE_MASTER_FLAT, "MASTER FLAT")
        self.assertEqual(TYPE_MASTER_BIAS, "MASTER BIAS")

    def test_dark_matching_keywords(self):
        """Test dark matching keywords include required fields."""
        self.assertIn(KEYWORD_CAMERA, DARK_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_GAIN, DARK_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_OFFSET, DARK_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_SETTEMP, DARK_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_READOUTMODE, DARK_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_EXPOSURESECONDS, DARK_MATCHING_KEYWORDS)

    def test_flat_matching_keywords(self):
        """Test flat matching keywords include required fields."""
        self.assertIn(KEYWORD_CAMERA, FLAT_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_GAIN, FLAT_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_OFFSET, FLAT_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_SETTEMP, FLAT_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_READOUTMODE, FLAT_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_FILTER, FLAT_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_DATE, FLAT_MATCHING_KEYWORDS)

    def test_bias_matching_keywords(self):
        """Test bias matching keywords include required fields."""
        self.assertIn(KEYWORD_CAMERA, BIAS_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_GAIN, BIAS_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_OFFSET, BIAS_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_SETTEMP, BIAS_MATCHING_KEYWORDS)
        self.assertIn(KEYWORD_READOUTMODE, BIAS_MATCHING_KEYWORDS)


if __name__ == "__main__":
    unittest.main()
