"""
CLI entry point for ap-copy-master-to-blink

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import argparse
import sys
from pathlib import Path
from typing import Optional, Tuple

from ap_common import setup_logging, replace_env_vars, resolve_path

from . import config
from .config import EXIT_SUCCESS, EXIT_ERROR
from .orchestration import process_blink_directory
from .statistics import print_summary, get_exit_code


def validate_directories(
    library_dir: Path, blink_dir: Path
) -> Tuple[bool, Optional[str]]:
    """
    Validate that library and blink directories exist and are directories.

    Args:
        library_dir: Path to calibration library
        blink_dir: Path to blink directory tree

    Returns:
        Tuple of (is_valid, error_message)
        - is_valid: True if both directories are valid, False otherwise
        - error_message: Error message if invalid, None if valid
    """
    if not library_dir.exists():
        return False, f"Library directory does not exist: {library_dir}"

    if not library_dir.is_dir():
        return False, f"Library path is not a directory: {library_dir}"

    if not blink_dir.exists():
        return False, f"Blink directory does not exist: {blink_dir}"

    if not blink_dir.is_dir():
        return False, f"Blink path is not a directory: {blink_dir}"

    return True, None


def print_header(library_dir: Path, blink_dir: Path, dry_run: bool) -> None:
    """
    Print header before processing.

    Args:
        library_dir: Path to calibration library
        blink_dir: Path to blink directory tree
        dry_run: Whether this is a dry run
    """
    print(f"\n{'='*70}")
    print("ap-copy-master-to-blink")
    print(f"{'='*70}")
    print(f"Library: {library_dir}")
    print(f"Blink:   {blink_dir}")
    print(f"Dry-run: {dry_run}")
    print(f"{'='*70}\n")


def main() -> int:
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Copy master calibration frames from library to blink directories",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage
  python -m ap_copy_master_to_blink <library_dir> <blink_dir>

  # With dryrun
  python -m ap_copy_master_to_blink <library_dir> <blink_dir> --dryrun

  # With debug output
  python -m ap_copy_master_to_blink <library_dir> <blink_dir> --debug

  # Real example
  python -m ap_copy_master_to_blink \\
      "F:/Astrophotography/_Calibration Library" \\
      "F:/Astrophotography/RedCat51@f4.9+ASI2600MM/10_Blink"
        """,
    )

    parser.add_argument(
        "library_dir",
        type=str,
        help="Path to calibration library (supports env vars like $VAR or ${VAR})",
    )

    parser.add_argument(
        "blink_dir",
        type=str,
        help="Path to blink directory tree (supports env vars like $VAR or ${VAR})",
    )

    parser.add_argument(
        "--dryrun",
        action="store_true",
        help="Show what would be copied without actually copying files",
    )

    parser.add_argument(
        "--quiet",
        "-q",
        action="store_true",
        help="Suppress progress output",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging",
    )

    parser.add_argument(
        "--scale-dark",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="scale dark frames using bias compensation (allows shorter exposures). "
        "Default: exact exposure match only",
    )

    parser.add_argument(
        "--flat-state",
        type=str,
        default=None,
        metavar="PATH",
        help="Path to flat state YAML file. Enables flexible flat date "
        "matching with interactive selection when no exact date match "
        "exists. Without this option, only exact date matches are used.",
    )

    parser.add_argument(
        "--picker-limit",
        type=int,
        default=5,
        metavar="N",
        help="Max older/newer flat dates to show in interactive picker "
        "(default: 5). Only used with --flat-state.",
    )

    parser.add_argument(
        "--date-dir-pattern",
        type=str,
        default=config.DEFAULT_DATE_DIR_PATTERN,
        metavar="PATTERN",
        help="regex pattern to match date directory where masters are copied "
        '(default: "^DATE_.*"). Assumes other tools create matching directories.',
    )

    args = parser.parse_args()

    # Setup logging
    setup_logging(name="ap_copy_master_to_blink", debug=args.debug, quiet=args.quiet)
    setup_logging(name="ap_common", debug=args.debug, quiet=args.quiet)

    # Resolve paths (support environment variables)
    library_dir = Path(resolve_path(replace_env_vars(args.library_dir)))
    blink_dir = Path(resolve_path(replace_env_vars(args.blink_dir)))

    # Validate directories exist
    is_valid, error_message = validate_directories(library_dir, blink_dir)
    if not is_valid:
        print(f"Error: {error_message}", file=sys.stderr)
        return EXIT_ERROR

    # Print header
    if not args.quiet:
        print_header(library_dir, blink_dir, args.dryrun)

    # Resolve flat state path
    flat_state_path = None
    if args.flat_state:
        flat_state_path = Path(resolve_path(replace_env_vars(args.flat_state)))

    # Process blink directory
    stats = process_blink_directory(
        library_dir,
        blink_dir,
        dry_run=args.dryrun,
        quiet=args.quiet,
        scale_darks=args.scale_dark,
        flat_state_path=flat_state_path,
        picker_limit=args.picker_limit,
        date_dir_pattern=args.date_dir_pattern,
    )

    # Print summary
    if not args.quiet:
        print_summary(stats)

    # Determine exit code from statistics
    exit_code = get_exit_code(stats)

    if exit_code != EXIT_SUCCESS and not args.quiet:
        print("Warning: Some master frames are missing. Check logs above for details.")

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
