"""
CLI entry point for ap-copy-master-to-blink

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import argparse
import sys
from pathlib import Path

from ap_common import setup_logging, replace_env_vars, resolve_path

from .copy_masters import process_blink_directory


def main() -> int:
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Copy master calibration frames from library to blink directories",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage
  python -m ap_copy_master_to_blink <library_dir> <blink_dir>

  # With dry-run
  python -m ap_copy_master_to_blink <library_dir> <blink_dir> --dry-run

  # With debug output
  python -m ap_copy_master_to_blink <library_dir> <blink_dir> --debug

  # Real example
  python -m ap_copy_master_to_blink \\
      "F:/Astrophotography/_Calibration Library" \\
      "F:/Astrophotography/RedCat51@f4.9+ASI2600MM/10_Blink"
        """,
    )

    parser.add_argument(
        "library_dir",
        type=str,
        help="Path to calibration library (supports env vars like $VAR or ${VAR})",
    )

    parser.add_argument(
        "blink_dir",
        type=str,
        help="Path to blink directory tree (supports env vars like $VAR or ${VAR})",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be copied without actually copying files",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging",
    )

    args = parser.parse_args()

    # Setup logging
    log_level = "DEBUG" if args.debug else "INFO"
    setup_logging(log_level)

    # Resolve paths (support environment variables)
    library_dir = resolve_path(replace_env_vars(args.library_dir))
    blink_dir = resolve_path(replace_env_vars(args.blink_dir))

    # Validate directories exist
    if not library_dir.exists():
        print(
            f"Error: Library directory does not exist: {library_dir}", file=sys.stderr
        )
        return 1

    if not library_dir.is_dir():
        print(f"Error: Library path is not a directory: {library_dir}", file=sys.stderr)
        return 1

    if not blink_dir.exists():
        print(f"Error: Blink directory does not exist: {blink_dir}", file=sys.stderr)
        return 1

    if not blink_dir.is_dir():
        print(f"Error: Blink path is not a directory: {blink_dir}", file=sys.stderr)
        return 1

    # Process blink directory
    print(f"\n{'='*70}")
    print("ap-copy-master-to-blink")
    print(f"{'='*70}")
    print(f"Library: {library_dir}")
    print(f"Blink:   {blink_dir}")
    print(f"Dry-run: {args.dry_run}")
    print(f"{'='*70}\n")

    stats = process_blink_directory(library_dir, blink_dir, dry_run=args.dry_run)

    # Print summary
    print(f"\n{'='*70}")
    print("Summary")
    print(f"{'='*70}")
    print(f"Unique configurations processed: {stats['configs_processed']}")
    print("\nMasters copied:")
    print(f"  Darks:  {stats['darks_copied']}")
    print(f"  Biases: {stats['biases_copied']}")
    print(f"  Flats:  {stats['flats_copied']}")
    print("\nMissing masters:")
    print(f"  Darks:  {stats['darks_missing']}")
    print(f"  Biases: {stats['biases_missing']} (only needed for exposure mismatch)")
    print(f"  Flats:  {stats['flats_missing']}")
    print(f"{'='*70}\n")

    # Return non-zero if any masters were missing
    if stats["darks_missing"] > 0 or stats["flats_missing"] > 0:
        print("Warning: Some master frames are missing. Check logs above for details.")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
