"""
Configuration constants for ap-copy-master-to-blink

Generated By: Claude Code (Claude Sonnet 4.5)
"""

# Supported file extensions
SUPPORTED_EXTENSIONS = {".fits", ".fit", ".xisf"}

# FITS header keywords (normalized)
KEYWORD_TYPE = "type"
KEYWORD_CAMERA = "camera"
KEYWORD_OPTIC = "optic"
KEYWORD_FILTER = "filter"
KEYWORD_GAIN = "gain"
KEYWORD_OFFSET = "offset"
KEYWORD_SETTEMP = "settemp"
KEYWORD_READOUTMODE = "readoutmode"
KEYWORD_EXPOSURESECONDS = "exposureseconds"
KEYWORD_DATE = "date"
KEYWORD_FOCALLEN = "focallen"

# Master frame types
TYPE_MASTER_DARK = "MASTER DARK"
TYPE_MASTER_FLAT = "MASTER FLAT"
TYPE_MASTER_BIAS = "MASTER BIAS"

# Matching keywords for each master type
DARK_MATCHING_KEYWORDS = [
    KEYWORD_CAMERA,
    KEYWORD_GAIN,
    KEYWORD_OFFSET,
    KEYWORD_SETTEMP,
    KEYWORD_READOUTMODE,
    KEYWORD_EXPOSURESECONDS,
]

FLAT_MATCHING_KEYWORDS = [
    KEYWORD_CAMERA,
    KEYWORD_OPTIC,
    KEYWORD_FILTER,
    KEYWORD_GAIN,
    KEYWORD_OFFSET,
    KEYWORD_SETTEMP,
    KEYWORD_READOUTMODE,
    KEYWORD_FOCALLEN,
    KEYWORD_DATE,  # Must match exactly
]

BIAS_MATCHING_KEYWORDS = [
    KEYWORD_CAMERA,
    KEYWORD_GAIN,
    KEYWORD_OFFSET,
    KEYWORD_SETTEMP,
    KEYWORD_READOUTMODE,
]
